### ISSUE TITLE
Feedbacks

### ISSUE THREAD

**Issue by yvan-sraka** [TheoHd/crab-cleaner#2]
Hello, **Group 1 (CILINGIR Elif, MZABI Hakim, HUCHARD Théo, HUANG Chaofu)**, Here some feedbacks about your submission:

I really like the fact you provide a custom project from your own idea with the will of continuing the project after the semester! Your project was well written, well documented, compile with no warnings, follow code styles standard of `cargo fmt`.

You write a good `README.md` (but why use an image like https://i.imgur.com/XeXiOR3.png when you can do ASCII art instead 😅) and provide a large test suite :

```
❯ cargo test
   Compiling crabcleaner v0.1.0 (/Users/yvan/project2/crab-cleaner)
    Finished test [unoptimized + debuginfo] target(s) in 4.36s
     Running target/debug/deps/crabcleaner-060b758dfd956225

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/crabcleaner-a0df50cd49fda317

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/app_test-476f275c49e9ae42

running 8 tests
test app_conf_file_lines_works ... ok
test app_cli_works_for_first_arg ... ok
test app_cli_works_for_second_arg ... ok
test app_execute_configurations_works ... ok
test app_get_arg_works ... ok
test app_default_conf_lines_works ... FAILED
test app_get_configurations_works ... FAILED
test app_get_configuration_works ... FAILED

failures:

---- app_default_conf_lines_works stdout ----
thread 'app_default_conf_lines_works' panicked at 'Could not find a configuration file in the current directory.', src/app.rs:115:9

---- app_get_configurations_works stdout ----
thread 'app_get_configurations_works' panicked at 'Could not find a configuration file in the current directory.', src/app.rs:115:9

---- app_get_configuration_works stdout ----
thread 'app_get_configuration_works' panicked at 'Could not find a configuration file in the current directory.', src/app.rs:115:9


failures:
    app_default_conf_lines_works
    app_get_configuration_works
    app_get_configurations_works

test result: FAILED. 5 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test app_test'
cargo test  8,26s user 1,30s system 216% cpu 4,412 total
```

You could for sure provide more features to your project, for e.g. be able to plug `crabcleaner` to something like `watchman` to have a `--daemon` mode and/or create for e.g. a `crabcleaner.service`, etc.

But considering the expectations of the semester, you achieved to get a good grade! Enjoy your vacations 🏖️

**Comment by TheoHd** [comment]
Thank you for your feedback, I am adding your ideas to the README.md and think it through.
Enjoy your vacations as well.
